name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -eo pipefail -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: pre-commit
        run: pre-commit run --all-files
